a = input('Digite algo:')
print(f'O tipo primitivo desse valor é: {type(a)}')
print(f'Só tem espações? {a.isspace()}')
print(f'É um numero? {a.isnumeric()}')
print(f'É alfabético? {a.isalpha()}')
print(f'É alfanumérico? {a.isalnum()}')
print(f'Esta em maiusculas? {a.isupper()}')
print(f'Esta em minusculas? {a.islower()}')
print(f'Esta capitalizado? {a.istitle()}')